#!/usr/bin/env bash


reg=""
cou=""
host=""
user=""
## y for UEFI n for bios or dos 
EFI=""
##
EFIpart=""
EFIdisk="" 

# change to true after you set the above variables
use="false"

export $user # to use it in other scripts
