#!/usr/bin/env bash


main() {

# => setup the localtime
read -p 'region: ' reg
read -p 'country: ' cou
ln -sf /usr/share/zoneinfo/$reg/$cou /etc/localtime

# => hardware clock
hwclock --systohc

# => localas
sed -i ' /s/#ar_SA.UTF-8 UTF-8/ar_SA.UTF-8 UTF-8/ ' /etc/locale.gen
sed -i ' /s/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/ ' /etc/locale.gen
locale-gen

# => hostname
read -p 'hostname: ' host
echo $host > /etc/hostname

# => users and passwords
# root password
passwd
# user groups and password
read -p 'username: ' user
useradd -m $user ; usermod -aG wheel,audio,video $user
passwd $user

# => sudoers

# => grub
read -p 'EFI or bios [y,n]: ' EFI

pacman -Syu grub efibootmgr os-prober dosfstools mtools --noconfirm

case $EFI in
    'y')
        read -p 'EFI partition mount point : ' EFIpart
        mount $EFIpart /boot/efi
        grub-install /boot/efi --recheck
        grub-mkconfig -o /boot/grub/grub.cfg
        ;;


    'n')
        read -p 'DISK(not the partition): ' EFIdisk
        grub-install $EFIdisk
        grub-mkconfig -o /boot/grub/grub.cfg
        ;;

esac

# => packages
pacman -Syu networkmanager xorg xorg-xinit xterm lightdm lightdm-gtk-greeter lightdm-webkit2-greeter openbox obconf picom lxappearance nitrogen kitty vim vifm htop geany pcmanfm firefox lsd bat starship github-cli  pipewire pipewire-pulse pipewire-alsa pipewire-jack pavucontrol wireplumber --noconfirm

# => network
sudo systemctl enable lightdm.service NetworkManager

}
