#!/usr/bin/env bash


# => setup the localtime
read -p 'region: ' reg
read -p 'country: ' cou
ln -sf /usr/share/zoneinfo/$reg/$cou /etc/localtime

# => hardware clock
hwclock --systohc

# => localas
sed -i ' /s/#ar_SA.UTF-8 UTF-8/ar_SA.UTF-8 UTF-8/ ' /etc/locale.gen
sed -i ' /s/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/ ' /etc/locale.gen
locale-gen

# => hostname
read -p 'hostname: ' host
echo $host > /etc/hostname

# => users and passwords
# root password
passwd
# user groups and password
read -p 'username: ' user
useradd -m $user ; usermod -aG wheel,audio,video $user
passwd $user

# => grup
read -p 'EFI or bios [y,n]: ' EFI

pacman -Syu grub efibootmgr os-prober dotfstools mtools --noconfirm

case $EFI in
    'y')
        read -p 'EFI partition: ' EFIpart
        mount $EFIpart /boot/efi
        grub-install /boot/efi --recheck
        grub-mkconfig -o /boot/grub/grub.cfg
        ;;


    'n')
        read -p 'ROOT DISK: ' EFIdisk
        grub-install $EFIdisk
        grub-mkconfig -o /boot/grub/grub.cfg
        ;;

esac

echo "Every thing DONE PLZ type exit and then umount -R 'your root partition'"
