#!/usr/bin/env bash

main() {

# setting the values
read -p 'region: ' reg
read -p 'country: ' cou
read -p 'hostname: ' host
read -p 'username: ' user
read -p 'EFI or bios [y,n]: ' EFI

# => setup the localtime
ln -sf /usr/share/zoneinfo/$reg/$cou /etc/localtime

# => hardware clock
hwclock --systohc

# => localas
sed -i ' s/#ar_SA.UTF-8 UTF-8/ar_SA.UTF-8 UTF-8/ ' /etc/locale.gen
sed -i ' s/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/ ' /etc/locale.gen
locale-gen

# => hostname
echo $host > /etc/hostname

# => users and passwords
# root password
passwd
# user groups and password
useradd -m $user ; usermod -aG wheel,audio,video $user
passwd $user

# => sudoers
sed -i 's/# %wheel ALL=(ALL:ALL) All/%wheel ALL=(ALL:ALL) All/' /etc/sudoers

# => grub
pacman -Syu grub efibootmgr os-prober dosfstools mtools --noconfirm

case $EFI in
    'y')
        read -p 'EFI partition: ' EFIpart
        mkdir -p /boot/efi
	    mount $EFIpart /boot/efi
        grub-install /boot/efi --recheck
        grub-mkconfig -o /boot/grub/grub.cfg
        ;;


    'n')
        read -p 'DISK(not the partition): ' EFIdisk
        grub-install $EFIdisk
        grub-mkconfig -o /boot/grub/grub.cfg
        ;;
     
     *)
	   echo "!@!#$@!" > /dev/null
	;;

esac

# => packages
pacman -Syu \
	xorg xorg-xinit xterm \
    sddm openbox awesome polkit polkit-kde-agent \
	obconf picom lxappearance nitrogen sxhkd \
    networkmanager bluez bluez-utils xf86-input-libinput\
	pipewire pipewire-pulse pipewire-alsa pipewire-jack pavucontrol wireplumber \
    alsa-utils alsa-firmware alsa-ucm-conf sof-firmware  \
    alacritty vim vifm htop lsd bat plocate \
    cbatticon wget unzip github-cli dunst bash-completion \
	geany sxiv pcmanfm firefox rofi \
	--noconfirm

# => system services
systemctl enable sddm NetworkManager

}
