#!/usr/bin/env bash

source "$(dirname $0)/conf"

aura-install () {

    git clone https://aur.archlinux.org/aura-bin.git

    chmod 777 aura-bin
    chown $user aura-bin
    chgrp users aura-bin
    cd aura-bin

    sudo -u $user makepkg --install
    cd ../ && sudo rm -rf aura-bin

}

configs() {


    dir=/home/$user
    git clone -q https://github.com/sirdonvua/mydotfiles
    mv mydotfiles $dir/dotfiles 

    mv $dir/.bashrc /tmp/
    cd $dir/dotfiles/
    stow -v . -t $dir

}

nerd_fonts() {

    #setup everything
    fonts=("CascadiaCode" "Inconsolata" "Hermit" "JetBrainsMono" "UbuntuMono" "Noto" )
    
    #Downloading the fonts
    for font in ${fonts[@]} ; do    
        
        echo "Downloading $font"
        aria2c -q "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/${font}.zip" \
            -d "/tmp"

        unzip -o "/tmp/${font}.zip" -d "/tmp/" &> /dev/null
        rm -rf "/tmp/${font}.zip" &> /dev/null
        
        echo "$font Downloaded"

    done
    
    #delete windows fonts
    ls /tmp | grep 'Windows' | xargs -I x rm /tmp/x

    #install the fonts
    mkdir -p /home/$user/.local/share/fonts
    ls /tmp | grep "Font" | xargs -I x mv /tmp/x /home/$user/.local/share/fonts
    fc-cache -f
    echo "all fonts installed"

}
