#!/usr/bin/env bash

source "$(dirname $0)/conf"

aura-install () {

    git clone -q https://aur.archlinux.org/aura-bin.git
    git clone -q https://aur.archlinux.org/thorium-browser-bin.git

    # aura
    chmod 777 aura-bin ; chown $user aura-bin ; chgrp users aura-bin ; cd aura-bin
    sudo -u $user makepkg --install
    cd ../ ; rm -rf aura-bin

    # Thorium browser
    chmod 777 thorium-browser-bin ; chown $user thorium-browser-bin ; chgrp users thorium-browser-bin ; cd thorium-browser-bin
    sudo -u $user makepkg --install
    cd ../ ; rm -rf thorium-browser-bin

}

configs() {


    dir=/home/$user
    sudo -u $user git clone -q https://github.com/sirdonvua/mydotfiles $dir/dotfiles

    mv $dir/.bashrc /tmp/
    cd $dir/dotfiles/
    sudo -u $user stow -v . -t $dir

}

nerd_fonts() {

    #setup everything
    fonts=("CascadiaCode" "Inconsolata" "Hermit" "JetBrainsMono" "UbuntuMono" "Noto" )
    
    #Downloading the fonts
    for font in ${fonts[@]} ; do    
        
        echo "Downloading $font"
        aria2c -q "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/${font}.zip" \
            -d "/tmp"

        unzip -o "/tmp/${font}.zip" -d "/tmp/" &> /dev/null
        rm -rf "/tmp/${font}.zip" &> /dev/null
        
        echo "$font Downloaded"

    done
    
    #delete windows fonts
    ls /tmp | grep 'Windows' | xargs -I x rm /tmp/x

    #install the fonts
    sudo -u $user mkdir -p /home/$user/.local/share/fonts
    ls /tmp | grep "Font" | xargs -I font-name mv /tmp/font-name /home/$user/.local/share/fonts
    sudo -u $user fc-cache -f
    echo "all fonts installed"

}

wallpapers () {
    # installing the wallpapers
    sudo -u $user git clone -q https://github.com/sirDonVua/wallpapers.git /home/$user/.local/share/wallpapers
    sudo -u $user mkdir -p /home/$user/.config/nitrogen
    sudo -u $user touch /home/$user/.config/nitrogen/nitrogen.cfg
    sudo -u $user touch /home/$user/.config/nitrogen/bg-saved.cfg

    # generating nitrogen configs 
    echo "
[geometry]
posx=0
posy=24
sizex=1918
sizey=1054

[nitrogen]
view=icon
recurse=true
sort=alpha
icon_caps=false
dirs=/home/$user/.local/share/wallpapers;" >> /home/$user/.config/nitrogen/nitrogen.cfg

    echo "
[xin_-1]
file=/home/$user/.local/share/wallpapers/05.png
mode=0
bgcolor=#000000" >> /home/$user/.config/nitrogen/bg-saved.cfg
    
}
