#!/usr/bin/env bash


aura-install () {

    source "$(dirname $0)/conf"
    git clone https://aur.archlinux.org/aura-bin.git

    chmod 777 aura-bin
    chown $user aura-bin
    chgrp users aura-bin
    cd aura-bin

    sudo -u $user makepkg --install
    cd ../ && sudo rm -rf aura-bin

}

configs() {

    source "$(dirname $0)/conf"

    dir=/home/$user
    git clone -q https://github.com/sirdonvua/mydotfiles

    sudo mv $dir/.bashrc /tmp/
    cd $dir/mydotfiles/
    stow -v . -t $dir

}
