#!/usr/bin/env bash
			
# => SOURCING THE FUNCTIONS
dir="$(dirname $0)"

. $dir/main
. $dir/func

while getopts  "c r m f h"  flag
do 

	case "${flag}" in 

#--------------------------------------------
		'r')
		    main
		    configs
		    nerd_fonts
		    wallpapers
	            ;;
#--------------------------------------------

		'm')
		    main
		    ;;
#--------------------------------------------
		'c')
		    configs
		    ;;
#--------------------------------------------
		'f')
		    nerd_fonts
		    ;;
#--------------------------------------------
		'h' | *)

		echo '
        available argument:
            -c : my config files
            -m : main
	    -r : recommended
            -f : nerd fonts
        '
#--------------------------------------------
    esac
done
