#!/usr/bin/env bash
			
# => SOURCING THE FUNCTIONS
dir="$(dirname $0)"

. $dir/func/Arch/main
. $dir/func/fonts
. $dir/func/config-files

while getopts  "c r m f h"  flag
do 

	case "${flag}" in 

#--------------------------------------------
		'r')
		    main-full
		    configs
		    nerd_fonts
	            ;;
#--------------------------------------------

		'm')
		    main
		    ;;
#--------------------------------------------
		'c')
		    configs
		    ;;
#--------------------------------------------
		'f')
		    nerd_fonts
		    ;;
#--------------------------------------------
		'a')
		    main
		    main-full
		    configs
		    nerd_fonts
		    ;;
#--------------------------------------------
		'h' | *)

		echo '
        available argument:
            -c : my config files
            -m : main
	    -r : recommended
            -f : nerd fonts'
		    ;;

#--------------------------------------------
    esac
done
