#!/bin/bash -i 
			
# shellcheck source=SCRIPTDIR/func/nala.sh
. func/nala.sh 
. func/deb-get.sh
. func/extrapkg.sh 
. func/nix.sh 
. func/gaming.sh

while getopts  "a b d e n g h"  flag
do 

	case "${flag}" in 
		
        'b')
            nala
            reboot=1
	    ;;
#############################################
		'd')
            deb-get
		;;

#############################################
		'e')
           nala-minimal && deb-get-minimal && extra
	    ;;
#############################################
		'n' ) 
            nix
        ;;
#############################################
		'g')
            nala-minimal && deb-get-minimal && gaming
	    ;;	
#############################################
        'a')
            nala
            deb-get
            extra
            gaming
            reboot=1
        ;;
#############################################
		'h' | *)

		echo 'available argument:
		-a : all
		-b : basics(nala)
		-d : deb-get
		-e : extra pkgs
		-n : nix install
		-g : gameing packages with nix'
#############################################
    esac
done

eval "$(tail -n +10 < ~/.bashrc)"
#reboot if needed
if [[ $reboot == 1 ]] ;then
	read -r -p "Reboot ?[y/n] " reboot

	if [[ $reboot == y ]] ;then 
		
	    sudo reboot
	else
	    echo "Okay have a good day"
	fi
fi
