#!/usr/bin/env bash

main() {

    dir="$(dirname $0)"
    
    # setup the config file
    source $dir/conf
    [[ $use == "false" ]] && echo "pleaze edit $dir/conf file" && exit 0

    # => setup the localtime
    ln -sf /usr/share/zoneinfo/$reg/$cou /etc/localtime
    
    # => hardware clock
    hwclock --systohc
    
    # => localas
    sed -i ' s/#ar_SA.UTF-8 UTF-8/ar_SA.UTF-8 UTF-8/ ' /etc/locale.gen
    sed -i ' s/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/ ' /etc/locale.gen
    locale-gen
    
    # => hostname
    echo $host > /etc/hostname
    
    # => users and passwords

    # root password
    passwd
    # user
    useradd -m $user ; usermod -aG wheel,audio,video $user
    passwd $user
    
    # => sudoers
    sed -i 's/# %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/' /etc/sudoers
    
    #touchpad config
    mkdir -p /etc/X11/xorg.conf.d/
    cp $dir/files/30-touchpad.conf /etc/X11/xorg.conf.d/30-touchpad.conf
    
    # => grub
    pacman -Syu grub efibootmgr os-prober dosfstools mtools --noconfirm --needed
    
    case $EFI in
	'y')
            mkdir -p /boot/efi
	    mount $EFIpart /boot/efi
            grub-install /boot/efi --recheck
            grub-mkconfig -o /boot/grub/grub.cfg
            ;;
	
	
	'n')
            grub-install $EFIdisk
            grub-mkconfig -o /boot/grub/grub.cfg
            ;;
	
	*)
	    echo "!@!#$@!" > /dev/null
	    ;;
	
    esac
    
    # => packages
    pacman -Syu - < $dir/PKGS --noconfirm --needed

    # => aura pacman wrapper and an aur helper
    su $user -c "cd ; git clone https://aur.archlinux.org/aura-bin.git ;
    cd aura-bin ;
    makepkg;"
    cd /home/$user/aura-bin/ && pacman -U *.zst --noconfirm --needed
    cd ../ && rm -rf aura-bin

    # nerd fonts
    aura -A nerd-fonts-complete --noconfirm
    
    # dotfiles
    su $user -c "cd ; git clone https://github.com/sirDonVua/mydotfiles ;
    cd mydotfiles ;
    rm -rf README.md ~/.bashrc ;
    stow . -t ~/ " # make a symlinks for the dot files
    
    # => system services
    systemctl enable libvirtd sddm NetworkManager bluetooth
    
    #init script
    mkdir -p /home/$user/.config/autorun
    chmod +x $dir/files/init.sh
    cp $dir/files/init.sh /home/$user/.config/autorun
    
}
