#!/usr/bin/env bash

backup () {
    for i in $@ ; do
        mv $HOME/$i $HOME/$i.bak
    done
}
    
configs() {

    backup .bashrc .bashrc-func .vimrc
    wget https://raw.githubusercontent.com/sirDonVua/mydotfiles/main/.bashrc -O $HOME/.bashrc
    wget https://raw.githubusercontent.com/sirDonVua/mydotfiles/main/.bashrc-func -O $HOME/.bash-func
    wget https://raw.githubusercontent.com/sirDonVua/mydotfiles/main/.vimrc -O $HOME/.vimrc

}
