#!/usr/bin/env bash


configs() {

    dir=$(dirname $0)
    mkdir -pv ~/.config
    git clone -q https://github.com/sirDonVua/mydotfiles

    cd $dir/mydotfiles/
    rm -rf .git README.md
    mv -f .config/* $HOME/.config
    ls -A | xargs -I x mv -f x ~/

    cd ../
    rm -rf $dir/mydotfiles

}
