#!/usr/bin/env bash


configs() {

    dir=$(dirname $0)
    mkdir -pv ~/.config
    git clone https://github.com/sirDonVua/mydotfiles

    rm -rf  $dir/mydotfiles/README.md
    mv -f $dir/mydotfiles/.config/* ~/.config/
    mv -f $dir/mydotfiles/* ~/
    rm -rf $dir/mydotfiles
    
}
