#!/usr/bin/env bash


extra() {
    
    #starship prompt
    curl -sS https://starship.rs/install.sh | sh

    #vim-plug
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

}
