#!/usr/bin/env bash


nerd_fonts() {

    #setup everything
    fonts=("CascadiaCode" "Inconsolata" "Hermit" "JetBrainsMono" "UbuntuMono" "Noto" )
    dir="/home/$user/.local/share/fonts"
    mkdir -p $dir
    
    #Downloading the fonts
    for font in ${fonts[@]} ; do    
        
        echo "Downloading $font"
        aria2c -q "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/${font}.zip" \
            -d $dir

        unzip -o "/tmp/${font}.zip" -d $dir &> /dev/null
        rm -rf "/$dir/${font}.zip" &> /dev/null
        
        echo "$font Downloaded"

    done
    
    #delete windows fonts
    ls $dir | grep 'Windows' | xargs -I x rm /$dir/x

    #install the fonts
    fc-cache -f
    echo "all fonts installed"

}
