#!/usr/bin/env  bash


main() {

    #git
    sudo dnf install git gh -y
    
    #Nerdy Stuff 
    sudo dnf install vim vifm htop cmatrix -y

    #Fancy Stuff
    sudo dnf install cowsay lolcat figlet starship -y

    #better ls and cat
    sudo dnf install lsd bat -y

    #brave browser
    sudo dnf install dnf-plugins-core
    sudo dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/
    sudo rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    
    sudo dnf install brave-browser -y

    #virt-manager
    sudo dnf install virt-manager && sudo systemctl enable libvirtd

}
