#!/usr/bin/env bash

main() {

    #extra cool packages
	sudo nala install git gh vim vifm htop cmatrix cowsay lolcat figlet -y
	sudo deb-get install brave-browser lsd bat zoom
   	
    #virt manager
    sudo nala install virt-manager && sudo systemctl enable libvirtd

    #starship prompt
    curl -sS https://starship.rs/install.sh | sh
}
